CREATE TABLE PRODUTOS(
	ID_PRODUTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME_PRODUTO varchar(255) NOT NULL,
	ESTOQUE_MINIMO integer(255) NOT NULL,
	ESTOQUE_MAXIMO integer(255) NOT NULL,
	VALOR_UNITARIO decimal(20) NOT NULL,
	QUANTIDADE integer(255) NOT NULL
)