CREATE TABLE CLIENTES(
	ID_CLIENTE int PRIMARY KEY AUTO_INCREMENT,
	NOME_CLIENTE VARCHAR(255) NOT NULL,
	ENDERECO_CLIENTE VARCHAR(255) NOT NULL,
	TELEFONE_CLIENTE VARCHAR(255) NOT NULL,
	EMAIL_CLIENTE VARCHAR(255) NOT NULL,
	CIDADE_CLIENTE VARCHAR(255) NOT NULL
)