<a href="./fornecedores.php">Cadastrar novo fornecedor</a>
<a href="../index.php">Voltar ao início</a>

FORNECEDORES CADASTRADOS
<?php
// SELECT * from FORNECEDORES ORDER by NOME_FORNCEDOR ASC
// SELECT NOME_FORNECEDOR, TELEFONE_FORNECEDOR, EMAIL_FORNECEDOR FROM FORNECEDORES ORDER BY NOME_FORNECEDOR_ASC

?>