CREATE TABLE CLIENTES(
	ID_CLIENTE int PRIMARY KEY,
	NOME_CLIENTE VARCHAR(255),
	ENDERECO_CLIENTE VARCHAR(255),
	TELEFONE_CLIENTE VARCHAR(255),
	EMAIL_CLIENTE VARCHAR(255),
	CIDADE_CLIENTE VARCHAR(255),
	
	
);