CREATE TABLE CLIENTES(
	ID_CLIENTE int PRIMARY KEY,
	NOME_CLIENTE VARCHAR(255) IS NOT NULL,
	ENDERECO_CLIENTE VARCHAR(255) IS NOT NULL,
	TELEFONE_CLIENTE VARCHAR(255) IS NOT NULL,
	EMAIL_CLIENTE VARCHAR(255) IS NOT NULL,
	CIDADE_CLIENTE VARCHAR(255) IS NOT NULL,	
);