CREATE TABLE FORNECEDOR(
	ID_FORNECEDOR INT PRIMARY KEY IS NOT NULL,
	NOME_FORNECEDOR VARCHAR(255) IS NOT NULL,
	TELEFONE_FORNECEDOR VARCHAR(255) IS NOT NULL,
	EMAIL_FORNECEDOR VARCHAR(255) IS NOT NULL,
	
);
