CREATE TABLE PRODUTOS(
	ID_PRODUTO INT PRIMARY KEY IS NOT NULL,
	NOME_PRODUTO varchar(255) IS NOT NULL,
	ESTOQUE_MINIMO integer(255) IS NOT NULL,
	ESTOQUE_MAXIMO integer(255) IS NOT NULL,
	VALOR_UNITARIO integer(255) IS NOT NULL,
	QUANTIDADE integer(255)IS NOT NULL,

);