CREATE TABLE PRODUTOS(
	ID_PRODUTO INT PRIMARY KEY NOT NULL,
	NOME_PRODUTO varchar(255) NOT NULL,
	ESTOQUE_MINIMO integer(255) NOT NULL,
	ESTOQUE_MAXIMO integer(255) NOT NULL,
	VALOR_UNITARIO integer(255) NOT NULL,
	QUANTIDADE integer(255) NOT NULL
)