CREATE TABLE VENDAS(
	ID_VENDA int PRIMARY KEY NOT NULL,
	NOME_PRODUTO VARCHAR(255) NOT NULL,
	NOME_CLIENTE VARCHAR(255),
	QUANTIDADE_PRODUTO VARCHAR(255) NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_CLIENTE INT,
	
);