CREATE TABLE VENDAS(
	ID_VENDA int PRIMARY KEY IS NOT NULL,
	NOME_PRODUTO VARCHAR(255) IS NOT NULL,
	NOME_CLIENTE VARCHAR(255) IS NULL,
	QUANTIDADE_PRODUTO VARCHAR(255) NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_CLIENTE INT IS NULL,
	
);