CREATE TABLE VENDAS(
	ID_VENDA int PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME_PRODUTO VARCHAR(255) NOT NULL,
	NOME_CLIENTE VARCHAR(255) NULL,
	QUANTIDADE_PRODUTO VARCHAR(255) NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_CLIENTE INT NULL	
)