UPDATE CLIENTES 
	SET NOME_CLIENTE = "OK", 
	ENDERECO_CLIENTE = "RUA 30 DE MARCO", 
	TELEFONE_CLIENTE = "49988477611",
	EMAIL_CLIENTE = "teste@gmail.com",
	CIDADE_CLIENTE = "PAN"
	 WHERE ID_CLIENTE = 4;